### PR TITLE
Fix Session-Token key accessed without checks

### LINKED ISSUE #64: Undefined index with the session token using app token
I get PHP notice about an undefined `Session-Token` index when authenticating on the API when setting an application token (using `setAppToken()`).

    require_once __DIR__ . '/vendor/autoload.php';
    $client = new Glpi\Api\Rest\Client(
        'http://localhost/glpi/apirest.php/',
        new GuzzleHttp\Client()
    );
    $client->setAppToken('abcdef....');
    $client->initSessionByCredentials(
        'glpi',
        'glpi'
    );
    var_dump($client->getFullSession()['statusCode']);
    $client->killSession();
  
### Observed Results:

    PHP Notice:  Undefined index: Session-Token in .../myexample/vendor/glpi-project/php-library-glpi/src/Glpi/Api/Rest/Client.php on line 137
    PHP Stack trace:
    PHP   1. {main}() .../myexample/test.php:0
    PHP   2. Glpi\Api\Rest\Client->initSessionByCredentials() .../myexample/test.php:10
    PHP   3. Glpi\Api\Rest\Client->request() .../myexample/vendor/glpi-project/php-library-glpi/src/Glpi/Api/Rest/Client.php:81
    int(200)
  
### Expected behavior:

There should be not "PHP Notice", only:

    int(200)

If I disable the app_token filtering on GLPI server side and comment the `setAppToken()`` call, the PHP notice disappears.

I tried various settings and got the following:

| Application token filtering on server side | Calling `setAppToken()` | Result |
| ------------------------------------------ | ----------------------- | ------ |
| No | No | Works OK without notice/errors |
| No | Yes | *PHP Notice:  Undefined index: Session-Token* (in `Client.php:137`) and *PHP Notice:  Undefined index: ERROR_WRONG_APP_TOKEN_PARAMETER* (in `ErrorHandler.php:69`) and *PHP Fatal error:  Uncaught exception 'Exception'* (in `Client.php:8`) |
| Yes | No | Works OK, it rejects the client because no token was provided (*PHP Fatal error:  Uncaught exception 'Exception' with message 'The current API requires an App-Token header for using its methods.'*) |
| Yes | Yes | *PHP Notice:  Undefined index: Session-Token* |

### LINKED ISSUE #65: Cannot connect to API server using user token
I cannot connect to API using user token (`initSessionByUserToken()`): I get rejected by the server:

> One of theses parameter(s) is missing: login and password or user_token

### Reproduction code

    require_once __DIR__ . '/vendor/autoload.php';
    $client = new Glpi\Api\Rest\Client(
        'http://localhost/glpi/apirest.php/',
        new GuzzleHttp\Client()
    );
    $client->setAppToken('abcdef....');
    $client->initSessionByUserToken('secret');
    var_dump($client->getFullSession()['statusCode']);
    $client->killSession();
  
### Observed Results:

    PHP Fatal error:  Uncaught exception 'Exception' with message 'One of theses parameter(s) is missing: login and password or user_token' in .../myexample/vendor/glpi-project/php-library-glpi/src/Glpi/Api/Rest/Client.php on line 104
    Stack trace:
    #0 .../myexample/test.php(7): Glpi\Api\Rest\Client->initSessionByUserToken('secret')
    #1 {main}
      thrown in .../myexample/vendor/glpi-project/php-library-glpi/src/Glpi/Api/Rest/Client.php on line 104
  
### Expected behavior:

There should be not "PHP Fatal error", only:

    int(200)

It may be related/similar to http://forum.glpi-project.org/viewtopic.php?id=159187 which seems to question https://github.com/glpi-project/glpi/commit/5bd42841159cfc7d16ff8a4d7686bd2139ba5285.

Using:
* GLPI v9.2.2
* php-library-glpi v0.1.0

### PR DESCRIPTION
**Pull request by C-Duv**
### Changes description

It resolves the issue that caused *Undefined index: Session-Token* PHP notices.

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Closes #64

### CODE REVIEW

**Comment by DIOHz0r** [comment]
I recomend you to let this code as it is and solve first the issue with the init session action 'cause the Session-Token is always mandatory for call all GLPI Endpoints (excluding only for lostPassword and initSession).

**Comment by ajsb85** [comment]
Hi, @C-Duv 
Remove the prefix WIP when the PR is ready to review.
At the moment the Travis CI build failed.
Thank you very much.

File: src/Glpi/Api/Rest/Client.php [hunk 1]
```diff
@@ -82,7 +83,7 @@ public function initSessionByCredentials($user, $password) {
       if ($response->getStatusCode() != 200
          || !$this->sessionToken = json_decode($response->getBody()->getContents(), true)['session_token']) {
          $body = json_decode($response->getBody()->getContents());
-         throw new Exception(ErrorHandler::getMessage($body[0]));
+         throw new BadEndpointException(ErrorHandler::getMessage($body[0]));
```
Comment (btry) [inline src/Glpi/Api/Rest/Client.php]: The endpoint of this method is trivial and always exists. 

If the response is !== 200 then the er ror is not due to a bad endpoint. It would be more related to a bad request (malformed, or invalid credentials). Then the BadEndpointException is not a good name here.

File: src/Glpi/Api/Rest/Client.php [hunk 2]
```diff
@@ -101,7 +102,7 @@ public function initSessionByUserToken($userToken) {
...
```
Comment (btry) [inline src/Glpi/Api/Rest/Client.php]: Same  as above

File: src/Glpi/Api/Rest/Client.php [hunk 3]
```diff
@@ -115,7 +116,7 @@ public function killSession() {
       $response = $this->request('get', 'killSession');
       if ($response->getStatusCode() != 200) {
          $body = json_decode($response->getBody()->getContents());
-         throw new Exception(ErrorHandler::getMessage($body[0]));
+         throw new BadEndpointException(ErrorHandler::getMessage($body[0]));
```
Comment (btry) [inline src/Glpi/Api/Rest/Client.php]: same again

File: src/Glpi/Api/Rest/Client.php [hunk 4]
```diff
@@ -153,13 +155,14 @@ public function request($method, $uri, array $options = []) {
          $hasResponse = $e->hasResponse();
          $statusCode = ($hasResponse) ? $e->getResponse()->getStatusCode() : '500';
          $contents = ($hasResponse) ? $e->getResponse()->getReasonPhrase() : 'Request Error';
-         throw new Exception($contents, $statusCode);
+         throw new BadEndpointException($contents, $statusCode);
```
Comment (btry) [inline src/Glpi/Api/Rest/Client.php]: the phpdoc is wrong : this method returns a \Psr\Http\Message\ResponseInterface and nothing else.

If it does not returns an isntance of \Psr\Http\Message\ResponseInterface the method throws an exception. No mixed not null

**Review by btry — CHANGES_REQUESTED** [review]
exceptions classes are not good

**Comment by DIOHz0r** [comment]
@btry I'm leaving the old code as it was and only fix a problem with the change made by @C-Duv. The change for your comments will be on another PR.

**Comment by btry** [comment]
Thank you @DIOHz0r . Don't forget to use a more accurate name for exceptions.

**Review by btry — DISMISSED** [review]
LGTM

**Comment by btry** [comment]
@DIOHz0r 

can you run git rebase HEAD^^ -i to edit the message of the 1st commit and add a Signed-Off-By tag for @C-Duv ?

**Review by DIOHz0r — APPROVED** [review]
